#!/usr/bin/env bun
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

interface RunResult {
  stdout: string
  stderr: string
}

const projectRoot = resolve(import.meta.dir, '..')
const demoRoot = join(projectRoot, '.demo')
const repoPath = join(demoRoot, 'jjgui-demo')
const remotePath = join(demoRoot, 'jjgui-demo-remote.git')

const args = new Set(Bun.argv.slice(2))
const shouldReset = args.has('--reset')
const shouldOpen = args.has('--open')

async function run(command: string[], cwd = projectRoot): Promise<RunResult> {
  const proc = Bun.spawn(command, {
    cwd,
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])

  if (exitCode !== 0) {
    throw new Error([
      `Command failed: ${command.join(' ')}`,
      stdout.trim(),
      stderr.trim(),
    ].filter(Boolean).join('\n'))
  }

  return { stdout, stderr }
}

async function jj(command: string[]): Promise<RunResult> {
  return run(['jj', ...command], repoPath)
}

function writeRepoFile(path: string, content: string): void {
  const fullPath = join(repoPath, path)
  mkdirSync(dirname(fullPath), { recursive: true })
  writeFileSync(fullPath, content)
}

async function changeId(rev = '@'): Promise<string> {
  const result = await jj(['log', '-r', rev, '--no-graph', '-T', 'change_id.shortest(8)'])
  return result.stdout.trim()
}

async function describe(message: string): Promise<string> {
  await jj(['describe', '-m', message])
  return changeId()
}

async function createDemoRepo(): Promise<void> {
  if (shouldReset) {
    rmSync(repoPath, { recursive: true, force: true })
    rmSync(remotePath, { recursive: true, force: true })
  }

  mkdirSync(demoRoot, { recursive: true })

  if (existsSync(repoPath)) return

  await run(['git', 'init', '--bare', remotePath], demoRoot)
  await run(['jj', 'git', 'init', repoPath], demoRoot)

  writeRepoFile('README.md', `# jjgui demo shop

This disposable repository is generated by \`bun run demo:repo\`.
Use it to try graph navigation, file diffs, bookmarks, rebases, and pushes
without touching the jjgui source repository.
`)
  writeRepoFile('src/app.ts', `export function renderHome() {
  return 'Welcome to the demo shop'
}
`)
  writeRepoFile('src/catalog.ts', `export const catalog = [
  { sku: 'desk-lamp', name: 'Desk lamp', price: 42 },
  { sku: 'notebook', name: 'Notebook', price: 12 },
]
`)
  writeRepoFile('docs/demo-script.md', `# Demo script

- Inspect the commit graph and colored lanes.
- Open changed files from feature commits.
- Move a bookmark.
- Push a local feature bookmark to the local origin remote.
- Use operation history to preview and revert a safe operation.
`)
  const base = await describe('Initialize demo storefront')
  await jj(['bookmark', 'create', 'main', '-r', base])
  await jj(['git', 'remote', 'add', 'origin', remotePath])
  await jj(['git', 'push', '--remote', 'origin', '-b', 'main'])

  await jj(['new', base])
  writeRepoFile('src/dashboard.ts', `export interface DashboardMetric {
  label: string
  value: number
}

export const metrics: DashboardMetric[] = [
  { label: 'Open changes', value: 7 },
  { label: 'Bookmarks', value: 4 },
]
`)
  const dashboardShell = await describe('Add dashboard metrics shell')

  await jj(['new', dashboardShell])
  writeRepoFile('src/dashboard.ts', `export interface DashboardMetric {
  label: string
  value: number
  trend: 'up' | 'down' | 'flat'
}

export const metrics: DashboardMetric[] = [
  { label: 'Open changes', value: 7, trend: 'up' },
  { label: 'Bookmarks', value: 4, trend: 'flat' },
]
`)
  writeRepoFile('src/operations.ts', `export const recentOperations = [
  'describe commit',
  'move bookmark',
  'preview revert',
]
`)
  const dashboardFinal = await describe('Add operation drawer data')
  await jj(['bookmark', 'create', 'feature/dashboard', '-r', dashboardFinal])

  await jj(['new', base])
  writeRepoFile('src/search.ts', `export function searchCatalog(query: string, items: string[]) {
  const normalized = query.trim().toLowerCase()
  return items.filter((item) => item.toLowerCase().includes(normalized))
}
`)
  const searchCommit = await describe('Add catalog search helper')
  await jj(['bookmark', 'create', 'feature/search', '-r', searchCommit])

  await jj(['new', base])
  writeRepoFile('src/settings.ts', `export const settings = {
  currency: 'USD',
  showExperimentalActions: false,
}
`)
  const settingsCommit = await describe('Add settings defaults')
  await jj(['bookmark', 'create', 'feature/settings', '-r', settingsCommit])

  await jj(['new', dashboardFinal, settingsCommit])
  writeRepoFile('docs/release-plan.md', `# Release plan

1. Review dashboard metrics.
2. Verify settings defaults.
3. Push the feature bookmarks to the local origin remote.
`)
  const integrationCommit = await describe('Merge dashboard and settings demo')
  await jj(['bookmark', 'create', 'demo/integration', '-r', integrationCommit])

  await jj(['new', integrationCommit])
  writeRepoFile('scratchpad.md', `# Demo workspace

This file is intentionally left as a working-copy change.
Try opening it in jjgui, moving it into another commit, or discarding it.
`)
  await describe('Demo workspace scratchpad')
}

await createDemoRepo()

const status = await jj(['st'])
console.log(`demo repo: ${repoPath}`)
console.log(`local remote: ${remotePath}`)
console.log(status.stdout.trim())

if (shouldOpen) {
  console.log('opening jjgui...')
  await run(['bun', 'run', 'bin/jjgui.ts', repoPath], projectRoot)
}
